# Created by VadNiks on Jul 31 2022
# Copyright (C) 2018-2023 Vad Nik (https://github.com/vadniks).
#
# This is an open-source project, the repository is located at https://github.com/vadniks/OpenNotesMirror.
# No license provided, so distribution, redistribution, modifying and/or commercial use of this code,
# without author's written permission, are strongly prohibited.
#
# Source codes are opened only for review.

name: notes_next_gen

publish_to: 'none'

version: 3.2.1+21

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/SourceCodePro-Regular.ttf
